---
# System Configuration
timezone: "UTC"
create_user: "admin"
# List of additional system packages to install
system_packages:
  - curl
  - vim
  - htop
  - git
  - python3-pip
  - ufw

# Docker Configuration
docker_compose_version: "2.32.4"
docker_users:
  - "{{ create_user }}"